CREATE TABLE raid_type (
  id BIGINT PRIMARY KEY,
  name VARCHAR,
  message VARCHAR,
  area VARCHAR,
  subarea VARCHAR,
  window_min INT,
  window_max INT,
  event_start DATE,
  event_end DATE
);
CREATE TABLE raid (
  raid_id UUID PRIMARY KEY,
  raid_type_id BIGINT,
  area VARCHAR,
  subarea VARCHAR,
  start_date TIMESTAMPTZ
);

INSERT INTO raid_type(id, name, message, area, subarea, window_min, window_max, event_start, event_end) VALUES
  (1,'?','A troll is happily trolling the Orc Fortress - somebody call the CMs!',NULL,NULL,NULL,NULL,NULL,NULL),
  (2,'?','A mummy has appeared somewhere east of Grizzly Adams... start counting!',NULL,NULL,NULL,NULL,NULL,NULL),
  (3,'?','A War Golem has appeared south-west of Svargrond.',NULL,NULL,NULL,NULL,NULL,NULL),
  (4,'?','A strange ghost has appeared somewhere in the deepling area. This calls for an experienced ghost hunter!',NULL,NULL,NULL,NULL,NULL,NULL),
  (5,'?','The birds in the forest below the Outlaw Camp have stopped to sing. There''s gonna be a riot here soon.',NULL,NULL,NULL,NULL,NULL,NULL),
  (6,'?','A muse has appeared south of Vengoth castle and creative energy is starting to form.',NULL,NULL,NULL,NULL,NULL,NULL),
  (7,'?','A bug has appeared in Stonehome. Testers, to the rescue!',NULL,NULL,NULL,NULL,NULL,NULL),
  (10,'Dragons in Draconia','There are dragons rising in Draconia!','Ab''Dendriel','Draconia',NULL,NULL,NULL,NULL),
  (11,'Wasps and Bears near Ab''Dendriel','Forest animals spread out close to Ab''Dendriel!','Ab''Dendriel','Ab''Dendriel Surroundings',NULL,NULL,NULL,NULL),
  (12,'Grynch Clan Goblins in Ab''Dendriel','Goblins of the infamous Grynch Clan are invading Ab''Dendriel to steal all presents, beware!','Ab''Dendriel','Ab''Dendriel City',1,1,'2000-12-20','2000-12-27'),
  (13,'Wolves near Ab''Dendriel','Many aggressive beasts are roaming south of Ab''Dendriel! Take care!','Ab''Dendriel','Ab''Dendriel Surroundings',NULL,NULL,NULL,NULL),
  (15,'Ancient Scarabs underground','Something is crawling deep in the Ankrahmun Scarab caves.','Southern Darama','Southern Darama Desert',NULL,NULL,NULL,NULL),
  (16,'Bonebeasts in the Mountain Tomb','Bonebeasts are rattling down in the Ankrahmun Dipthrah tombs.','Southern Darama','Ankrahmun Pharaoh Tombs',NULL,NULL,NULL,NULL),
  (17,'Cobras in the Mountain Tomb','There''s something sizzling in the Ankrahmun Dipthrah tombs.','Southern Darama','Ankrahmun Pharaoh Tombs',NULL,NULL,NULL,NULL),
  (18,'Djinns','There is a sudden rise in djinn population in Kha''zeel!','Northern Darama','Ashta''daramai',NULL,NULL,NULL,NULL),
  (20,'Gargoyles in the Oasis Tomb','There is something stony moving down in the Ankrahmun Rahemos tombs.','Southern Darama','Ankrahmun Pharaoh Tombs',NULL,NULL,NULL,NULL),
  (21,'Grynch Clan Goblins in Ankrahmun','Goblins of the infamous Grynch Clan are invading Ankrahmun to steal all presents, beware!','Southern Darama','Ankrahmun City',1,1,'2000-12-20','2000-12-27'),
  (22,'Necromancers in the Peninsula Tomb','Necromancer attack in the Ankrahmun Omruc tombs!','Southern Darama','Ankrahmun Pharaoh Tombs',NULL,NULL,NULL,NULL),
  (23, 'Nomads in Ankrahmun', 'Nomad scouts have been sighted close to the gates to Ankrahmun.', 'Southern Darama', 'Southern Darama Desert', 6, 8, NULL, NULL),
  (24,'Scarabs near Ankrahmun','Unusual frequent scarab sightings at the gates of Ankrahmun.','Southern Darama','Southern Darama Desert',NULL,NULL,NULL,NULL),
  (25,'Slimes in the Shadow Tomb','There is something slimy going on in the Ankrahmun Mahrdis tombs.','Southern Darama','Ankrahmun Pharaoh Tombs',NULL,NULL,NULL,NULL),
  (26,'Terramites near Ankrahmun','Something is moving under the surface in the sand north of Ankrahmun!','Southern Darama','Southern Darama Desert',NULL,NULL,NULL,NULL),
  (27,'Skeletons north of Ankrahmun','Some skeletons are assembling north of Ankrahmun!','Southern Darama','Southern Darama Desert',NULL,NULL,NULL,NULL),
  (28,'Vampires in the Shadow Tomb','Cold bodies with long teeth have lowered the temperature down in the Ankrahmun Mahrdis tombs.','Southern Darama','Ankrahmun Pharaoh Tombs',NULL,NULL,NULL,NULL),
  (29,'Vampires in the Tarpit Tomb','There''s a sudden ice cold wind in the Ankrahmun Morguthis tombs!','Southern Darama','Ankrahmun Pharaoh Tombs',NULL,NULL,NULL,NULL),
  (32,'Barbarians near Svargrond','Scouts report a barbarian army gathering near Svargrond.','Hrodmir','Svargrond Surroundings',NULL,NULL,NULL,NULL),
  (37,'Amazons north of Carlin','Amazons are converging north of Carlin.','Carlin','Fields of Glory',NULL,NULL,NULL,NULL),
  (39,'Grynch Clan Goblins in Carlin','Goblins of the infamous Grynch Clan are invading Carlin to steal all presents, beware!','Carlin','Carlin City',1,1,'2000-12-20','2000-12-27'),
  (40,'Orcs north of Carlin','Some orcs are assembling in the woods between Carlin and Northport.','Carlin','Fields of Glory',NULL,NULL,NULL,NULL),
  (42,'Trolls north of Carlin','Trolls trolling north-west of Carlin!','Carlin','Carlin Surroundings',NULL,NULL,NULL,NULL),
  (43,'Undead in the Ghostlands','There is a slight uneven energy in the ghostlands west of Carlin. Something is going to happen soon.','Carlin','Ghostlands',7,17,NULL,NULL),
  (44,'Willi Wasp','Some wasps have been found north of Carlin. There is some loud buzzing in the air.','Carlin','Carlin Surroundings',NULL,NULL,NULL,NULL),
  (55,'Ferumbras','The seals on Ferumbras'' old citadel are glowing. Prepare for HIS return, mortals.','Vandura','Kharos',NULL,NULL,NULL,NULL),
  (59,'Grynch Clan Goblins in Darashia','Goblins of the infamous Grynch Clan are invading Darashia to steal all presents, beware!','Northern Darama','Darashia City',1,1,'2000-12-20','2000-12-27'),
  (60,'Zomba','Hungry lions scout the western Darashian desert. Travellers beware!','Northern Darama','Northern Darama Desert',NULL,NULL,NULL,NULL),
  (61,'Minotaurs north of Darashia','Minotaurs call to arms in the north of Darashia!','Northern Darama','Daramian Minotaur Pyramid',NULL,NULL,NULL,NULL),
  (62,'Necromancers in the Catacombs','A necromancer prepares to wake the dead in a crypt below Darashia!','Northern Darama',NULL,NULL,NULL,NULL,NULL),
  (63,'Pirates north of Darashia','Pillage and plunder! Pirates have been sighted north of Darashia!','Northern Darama','Northern Darama Desert',NULL,NULL,NULL,NULL),
  (64,'Undead raid on Darashia','Hordes of undead invade from the west of Darashia!','Northern Darama','Northern Darama Desert',NULL,NULL,NULL,NULL),
  (66,'?','The Full Moon rises and werehyaenas are roaming the Northern Darama Desert!',NULL,NULL,NULL,NULL,NULL,NULL),
  (86,'Undead in Drefia','Undead spirits stalk the ruins of Drefia.','Northern Darama',NULL,3,9,NULL,NULL),
  (87,'Liches in Drefia','Mortals, beware. Liches are being summoned in Drefia''s Deeper Vampire Crypts.','Northern Darama',NULL,4,8,NULL,NULL),
  (89,'Priestesses in Drefia','The priestesses in Drefia call their sisters to wake dark powers. Fight their evil purpose!','Northern Darama',NULL,6,15,NULL,NULL),
  (91,'Pale Count','The Pale Count has risen from his crypt deep under Drefia. Blood will flow.','Northern Darama',NULL,16,30,NULL,NULL),
  (92,'Zombies in Drefia','One of the black rituals in Drefia has succeeded. Dead meat is walking the ritual halls.','Northern Darama',NULL,5,11,NULL,NULL),
  (93,'Dryads in Cormaya','Dryads have returned to protect their tree gardens underneath Cormaya.','Edron','none',1,1,'2000-06-01','2000-06-30'),
  (94,'Dryads in Edron','Dryads have returned to protect the forest north of Edron.','Edron','Edron Surroundings',1,1,'2000-06-01','2000-06-30'),
  (95,'Dryads in Ab''Dendriel','Dryads have returned to protect the northern forests near Ab''Dendriel.','Carlin','Fields of Glory',1,1,'2000-06-01','2000-06-30'),
  (96,'Dryads in Tiquanda','Dryads have returned to protect the jungle of Tiquanda.','Port Hope','Port Hope Surroundings',1,1,'2000-06-01','2000-06-30'),
  (99,'Goblins in Edron','Goblins are converging west of Edron.','Edron','Edron Surroundings',3,9,NULL,NULL),
  (100,'Grynch Clan Goblins in Edron','Goblins of the infamous Grynch Clan are invading Edron to steal all presents, beware!','Edron','Edron Castle',1,1,'2000-12-20','2000-12-28'),
  (101,'Hunters in Edron','Some hunters are roaming the woods north of Edron!','Edron','Edron Surroundings',5,15,NULL,NULL),
  (102,'Warlocks in Edron','Some monks have gathered at a stone circle northwest of Edron. They seem to be up to something.','Edron','Edron Surroundings',7,15,NULL,NULL),
  (103,'Orcs Berserkers in Edron Orc Cave','Deep under Edron, the orc population seems to grow rapidly. Be careful and take a rope with you!','Edron','Edron Orc Lands',4,9,NULL,NULL),
  (104,'Orshabaal','Orshabaal''s minions are working on his return to the World. LEAVE Edron at once, mortals.','Edron','Edron Surroundings',154,175,NULL,NULL),
  (111,'Wyverns in Edron','Shriiiiiek! What evil intentions do the wyverns have northwest of Edron?','Edron','Edron Surroundings',7,14,NULL,NULL),
  (116,'Essence of Darkness raid','One of the ten lights went dark and disappeared! All hope is lost now. Flee into your houses and hope to survive this day.',NULL,NULL,NULL,NULL,NULL,NULL),
  (122,'Devovorga','Devovorga has awoken.',NULL,NULL,NULL,NULL,NULL,NULL),
  (125,'Devovorga','Devovorga is raging!',NULL,NULL,NULL,NULL,NULL,NULL),
  (165,'Gaz''haragoth','Gaz''haragoth will shatter your dreams in a barrage of nightmares!',NULL,NULL,NULL,NULL,NULL,NULL),
  (166,'Banshees in The Ghostlands','A disturbance in the ether stirs up the undead of the Ghostlands.','Carlin','Ghostlands',51,52,NULL,NULL),
  (169,'Morgaroth','The ancient volcano on Goroma slowly becomes active once again.','Vandura','Hellgorge',168,175,NULL,NULL),
  (174,'Halloween Hare','Beware, beware the halloween hare.',NULL,NULL,NULL,NULL,NULL,NULL),
  (175,'Mutated Pumpkin','Oh noes! It''s a mutated pumpkin!',NULL,NULL,NULL,NULL,NULL,NULL),
  (180,'Ghazbaran','An ancient evil is awakening in the mines beneath Hrodmir.','Hrodmir',NULL,161,175,NULL,NULL),
  (181,'Bats in the Kazordoon mines','There seems to be a bat problem in the Kazordoon mines.','Kazordoon','Kazordoon Underground',11,11,NULL,NULL),
  (182,'Goblins on Femor Hills','Goblins are preparing to attack Kazordoon from Femor Hills!','Kazordoon','Femor Hills',5,7,NULL,NULL),
  (183,'Grynch Clan Goblins in Kazordoon','Goblins of the infamous Grynch Clan are invading Kazordoon to steal all presents, beware!','Kazordoon','Kazordoon City',1,1,'2000-12-20','2000-12-27'),
  (187,'Minotaurs in the Kazordoon mines','Kaplar! Flee before it is too late! Minos in the Kazordoon Mines!','Kazordoon','Horned Fox Lair',12,14,NULL,NULL),
  (189,'Hunters north of Green Claw Swamp','Hunters on the hunt north of the Green Claw Swamp.','Kazordoon','Kazordoon Surroundings',10,10,NULL,NULL),
  (193,'Grynch Clan Goblins in Liberty Bay','Goblins of the infamous Grynch Clan are invading Liberty Bay to steal all presents, beware!','Vandura','Liberty Bay City',1,1,'2000-12-20','2000-12-27'),
  (194,'Flamingoes on Laguna Islands','There has been an unnatural rise in flamingo population on the Laguna Islands.','Vandura','Laguna Islands',8,19,NULL,NULL),
  (195,'Pirate Bosses in Liberty Bay','Pirates are launching a surprise attack on Liberty Bay! Take care, they seem to be everywhere.','Vandura','Liberty Bay Surroundings',15,20,NULL,NULL),
  (196,'Pirates near Liberty Bay','Unknown ships are sighted north of Liberty Bay.','Vandura','Liberty Bay Surroundings',16,22,NULL,NULL),
  (197,'Quaras near Liberty Bay','Something is moving in the depths of the sea around Liberty Bay.','Vandura','Liberty Bay Surroundings',21,29,NULL,NULL),
  (198,'Quaras in plantations 1','Numerous Quara fins have been sighted in the seas around Liberty Bay.','Vandura','Liberty Bay Surroundings',40,55,NULL,NULL),
  (199,'Quaras in plantations 2','Numerous Quara fins have been sighted in the seas around Liberty Bay.','Vandura','Liberty Bay Surroundings',40,55,NULL,NULL),
  (200,'Quaras in plantations 3','Numerous Quara fins have been sighted in the seas around Liberty Bay.','Vandura','Liberty Bay Surroundings',40,55,NULL,NULL),
  (202,'Pirates in plantations','Sails sighted northwest of Liberty Bay.','Vandura','Liberty Bay Surroundings',14,18,NULL,NULL),
  (203,'Tortoises on Treasure Island','Slowly but steadily, the population of tortoises grows on Treasure Island.','Vandura','Treasure Island',6,15,NULL,NULL),
  (207,'Tigers on Meriana','Majestic creatures with stripes roam the small desert at Meriana.','Vandura','Meriana',3,8,NULL,NULL),
  (229,'Giant Spiders on the Plains of Havoc','The mating season of the giant spiders is at hand. Leave the plains of havoc as fast as you can.','Venore','Plains of Havoc',NULL,NULL,NULL,NULL),
  (235,'Undead on the Plains of Havoc','The dead of the plains of havoc are becoming restless!','Venore','Plains of Havoc',NULL,NULL,NULL,NULL),
  (237,'Kongras in Banuta','There are some kongras congregating south of Banuta.','Tiquanda','Banuta',NULL,NULL,NULL,NULL),
  (238,'Serpent Spawns in Deeper Banuta','Something bad is happening deep, deep down under Banuta.','Tiquanda','Banuta',NULL,NULL,NULL,NULL),
  (239,'Lizards near Port Hope','Lizards seem to attack Port Hope from Chor.','Tiquanda','Port Hope Surroundings',NULL,NULL,NULL,NULL),
  (240,'Grynch Clan Goblins in Port Hope','Goblins of the infamous Grynch Clan are invading Port Hope to steal all presents, beware!','Tiquanda','Port Hope City',1,1,'2000-12-20','2000-12-27'),
  (243,'Terrorbirds in Trapwood','Terrorbirds have been sighted in Trapwood south-east of Port Hope!','Tiquanda','Port Hope Surroundings',NULL,NULL,NULL,NULL),
  (257,'Grynch Clan Goblins in Rathleton','Goblins of the infamous Grynch Clan are invading Rathleton to steal all presents, beware!','Oramond','Rathleton City',1,1,'2000-12-20','2000-12-27'),
  (281,'Spectral Scum','Spectral scum is invading the towns! Ask a fortune teller for help!',NULL,NULL,NULL,NULL,NULL,NULL),
  (283,'Barbarians in Bittermor','Barbarians are gathering at Bittermor. They seem to be up to something.','Hrodmir','Bittermor',3,7,NULL,NULL),
  (284,'Grynch Clan Goblins in Svargrond','Goblins of the infamous Grynch Clan are invading Svargrond to steal all presents, beware!','Hrodmir','Svargrond City',1,1,'2000-12-20','2000-12-27'),
  (287,'Ice Golems in Formorgar Mines','There is a sudden rise in the ice golem population in Formorgar Mines.','Hrodmir',NULL,NULL,NULL,NULL,NULL),
  (289,'Winter Wolves in Krimhorn','Packs of winter wolves have been sighted roaming the area near the barbarian camps in Svargrond!','Hrodmir','Krimhorn',NULL,NULL,NULL,NULL),
  (293,'Rat plague','Rat plague in Thais!','Thais','Thais City',NULL,NULL,NULL,NULL),
  (294,'Cyclopses east of Thais','Let da mashing begin! Cyclops riot east of Thais.','Thais','Mount Sternum',NULL,NULL,NULL,NULL),
  (296,'Grynch Clan Goblins in Thais','Goblins of the infamous Grynch Clan are invading Thais to steal all presents, beware!','Thais','Thais City',1,1,'2000-12-20','2000-12-27'),
  (297,'Kingsday tomb creatures','The King''s mages have summoned some creatures from the tombs in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (298,'Kingsday dragon lords','The King''s mages have summoned some dragon lords in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (299,'Kingsday dragons','The King''s mages have summoned some dragons in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (300,'Kingsday dworcs','The King''s mages have summoned some dworcs in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (302,'Kingsday frost dragons','The King''s mages have summoned some frost dragons in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (303,'Kingsday goblins','The King''s mages have summoned some goblins in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (304,'Kingsday jungle','The King''s mages have summoned some creatures from the Tiquanda jungle in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (305,'Kingsday lizards','The King''s mages have summoned some lizards in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (306,'Kingsday minotaurs','The King''s mages have summoned some minotaurs in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (307,'Kingsday orcs','The King''s mages have summoned some orcs in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (308,'Kingsday trolls','The King''s mages have summoned some trolls in the knight''s arena for your enjoyment.',NULL,NULL,NULL,NULL,NULL,NULL),
  (310,'Orc raid on Thais','Orc activity near Thais reported! Beware!','Thais','Thais Surroundings',NULL,NULL,NULL,NULL),
  (311,'Weak orcs north of Thais','Some orcs are assembling north of Thais.','Thais','Thais Surroundings',NULL,NULL,NULL,NULL),
  (312,'Wasps south of Thais','Buzzing and humming! Wasps south of Thais. Be careful there!','Thais','Thais Surroundings',NULL,NULL,NULL,NULL),
  (313,'Lizard army raid on Port Hope','The lizards of Chor are amassing an army to take over the southern Jungle!','Tiquanda','Port Hope Surroundings',NULL,NULL,NULL,NULL),
  (322,'Undead Jesters in Ab''Dendriel','Oh no! Ab''Dendriel beware! All bad entertainers are returning from their graves to haunt their audience once again!','Ab''Dendriel','Ab''Dendriel City',1,1,'2000-04-01','2000-04-14'),
  (323,'Undead Jesters in Ankrahmun','Oh no! Ankrahmun beware! All bad entertainers are returning from their graves to haunt their audience once again!','Southern Darama','Ankrahmun City',1,1,'2000-04-01','2000-04-14'),
  (324,'Undead Jesters in Carlin','Oh no! Carlin beware! All bad entertainers are returning from their graves to haunt their audience once again!','Carlin','Carlin City',1,1,'2000-04-01','2000-04-14'),
  (325,'Undead Jesters in Darashia','Oh no! Darashia beware! All bad entertainers are returning from their graves to haunt their audience once again!','Northern Darama','Darashia City',1,1,'2000-04-01','2000-04-14'),
  (326,'Undead Jesters in Edron','Oh no! Edron beware! All bad entertainers are returning from their graves to haunt their audience once again!','Edron','Edron Castle',1,1,'2000-04-01','2000-04-14'),
  (327,'Undead Jesters in Kazordoon','Oh no! Kazordoon beware! All bad entertainers are returning from their graves to haunt their audience once again!','Kazordoon','Kazordoon City',1,1,'2000-04-01','2000-04-14'),
  (328,'Undead Jesters in Liberty Bay','Oh no! Liberty Bay beware! All bad entertainers are returning from their graves to haunt their audience once again!','Vandura','Liberty Bay City',1,1,'2000-04-01','2000-04-14'),
  (329,'Undead Jesters in Port Hope','Oh no! Port Hope beware! All bad entertainers are returning from their graves to haunt their audience once again!','Tiquanda','Port Hope City',1,1,'2000-04-01','2000-04-14'),
  (330,'Undead Jesters in Svargrond','Oh no! Svargrond beware! All bad entertainers are returning from their graves to haunt their audience once again!','Hrodmir','Svargrond City',1,1,'2000-04-01','2000-04-14'),
  (331,'Undead Jesters in Thais','Oh no! Thais beware! All bad entertainers are returning from their graves to haunt their audience once again!','Thais','Thais City',NULL,NULL,NULL,NULL),
  (332,'Undead Jesters in Yalahar','Oh no! Yalahar beware! All bad entertainers are returning from their graves to haunt their audience once again!','Yalahar','Yalahar Centre',NULL,NULL,NULL,NULL),
  (334,'Elves near Venore','Elven scouts from Shadowthorn have been spotted near Venore! Beware!','Venore','Venore City',NULL,NULL,NULL,NULL),
  (335,'Witches at Green Claw Swamp','Dark energy is concentrating in the Green Claw Swamp. Something is about to happen there.','Venore','Green Claw Swamp',NULL,NULL,NULL,NULL),
  (336,'Grynch Clan Goblins in Venore','Goblins of the infamous Grynch Clan are invading Venore to steal all presents, beware!','Venore','Venore City',1,1,'2000-12-20','2000-12-27'),
  (337,'Wyverns in Gnomebase Alpha','There is a sudden rise in wyvern population in the mushroom gardens beneath Gnomebase Alpha.','Kazordoon',NULL,NULL,NULL,NULL,NULL),
  (346,'Grynch Clan Goblins in Yalahar','Goblins of the infamous Grynch Clan are invading Yalahar to steal all presents, beware!','Yalahar','Yalahar Centre',1,1,'2000-12-20','2000-12-27'),
  (347,'Vampires in Yalahar','Citizens of Yalahar, beware! Harbingers of vampiric blood thirst are appearing in the city. Fight them or take your chance to flee while you still can.','Yalahar','Yalahar Centre',NULL,NULL,NULL,NULL),
  (350,'The Blightfather','Like a swarm of locusts the dreaded lancer beetles are pouring over the fertile parts of Zao.','Zao','Muggy Plains',NULL,NULL,NULL,NULL),
  (357,'Grand Mother Foulscale and Draptors','The dragons of the Dragonblaze Mountains have descended to Zao to protect the lizardkin!','Zao','Muggy Plains',NULL,NULL,NULL,NULL),
  (366,'Cublarc raid on Zao Steppe','An orcish horde, ready for murder and plunder, is amassing to begin its travel through the steppes of Zao. Beware!','Zao','Zao Steppe',NULL,NULL,NULL,NULL),
  (367,'Gnarlhounds on Zao Steppe','There seems to be a big gnarlhound gang in Zao Steppe.','Zao','Zao Steppe',NULL,NULL,NULL,NULL),
  (368,'Lancer Beetles on Zao Steppe','Lancer beetles troop up in Farmine. Beware!','Zao','Zao Steppe',NULL,NULL,NULL,NULL),
  (369,'Zzaion raid','A massive orc force is gathering at the gates of Zzaion.','Zao','Zao Steppe',NULL,NULL,NULL,NULL),
  (751,'The Abomination','Something abnominale is rising! Search for its spawns! Gather an army and destroy this threat!',NULL,NULL,NULL,NULL,NULL,NULL),
  (2232,'Morshabaal','Beware mortals! Orshabaal''s brother, the infamous Morshabaal is out for revenge and will spread fear for his family once again!',NULL,NULL,NULL,NULL,NULL,NULL),
  (2241,'Nimmersatt','The dragon Nimmersatt is distracted! Help to breach its lair! Join the heist at the coast north of Carlin!','Carlin','Ice Islands',152,208,NULL,NULL),
  (2253,'Rotrender','Rotrender has risen again in the depths of Azzilon.',NULL,NULL,NULL,NULL,NULL,NULL);
